### ISSUE TITLE
Seems to not be pulling latest emails, past few days were missed

### ISSUE THREAD

**Issue by francislavoie** [mnapoli/externals#173]
Last mail on https://externals.io/ is from 3 days ago, but there's been plenty in the past 2-3 days https://news-web.php.net/php.internals :scream:

**Comment by francislavoie** [comment]
Oh I think I see what happened, this one email is dated at unix epoch :scream: https://news-web.php.net/php.internals/117903

**Comment by mnapoli** [comment]
Ohhh awesome, thank you for debugging! Here is indeed what I see in the Lambda logs:

```
START RequestId: aa40095a-ff35-4808-89d9-1f01f656f2b6 Version: $LATEST
[INFO] Synchronizing message 117903
aa40095a-ff35-4808-89d9-1f01f656f2b6	Invoke Error	{...}
{
  "errorType": "Rvdv\\Nntp\\Exception\\SocketException",
  "errorMessage": "",
  "stack": [
    "#0 /var/task/vendor/rvdv/nntp/src/Connection/Connection.php(152): Rvdv\\Nntp\\Socket\\Socket->gets()",
    "#1 /var/task/vendor/rvdv/nntp/src/Connection/Connection.php(108): Rvdv\\Nntp\\Connection\\Connection->getMultiLineResponse()",
    "#2 /var/task/vendor/rvdv/nntp/src/Client.php(212): Rvdv\\Nntp\\Connection\\Connection->sendCommand()",
    "#3 /var/task/src/EmailSynchronizer.php(76): Rvdv\\Nntp\\Client->sendCommand()",
    "#4 /var/task/src/Application/Handler/SynchronizeHandler.php(18): Externals\\EmailSynchronizer->synchronize()",
    "#5 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Externals\\Application\\Handler\\SynchronizeHandler->handle()",
    "#6 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke()",
    "#7 /opt/bref/bootstrap.php(43): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
    "#8 {main}"
  ]
}
END RequestId: aa40095a-ff35-4808-89d9-1f01f656f2b6
REPORT RequestId: aa40095a-ff35-4808-89d9-1f01f656f2b6	Duration: 30750.58 ms	Billed Duration: 30751 ms	Memory Size: 1024 MB	Max Memory Used: 63 MB
```

I've just pushed https://github.com/mnapoli/externals/commit/5f5c3f2ffaf287e7998351b60bf4975fbc3c7533 to see if that solves it!

**Comment by francislavoie** [comment]
Nice, new messages are in

**Comment by mnapoli** [comment]
Awesome, and thanks a lot for the sponsorship! 💙

**Comment by francislavoie** [comment]
No, thank you for the service you're running! And thanks for PHP-DI which we use heavily at work :grinning:
